image: node:20-alpine

# Define stages for the pipeline
stages:
  - test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "web"
    
# Cache dependencies to speed up builds
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# Job for running tests and uploading coverage
variables:
  NEXT_TELEMETRY_DISABLED: "1"   # keep CI quiet

test-and-upload-coverage:
  stage: test
  script:
    # 0 — Install curl
    - apk add --no-cache curl
    
    # 1 — Install & test
    - npm ci
    - npm run test:coverage -- --maxWorkers=2

    # 2 — Download Codecov uploader (bash uploader is deprecated)
    - curl -Os https://cli.codecov.io/v10.4.0/alpine/codecov
    - chmod +x codecov

    # 3 — Upload the LCOV report
    - |
      # Pick the right variable for every pipeline type
      BRANCH_NAME="${CI_COMMIT_REF_NAME:-$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
    
      ./codecov upload-process -f coverage/lcov.info --git-service gitlab --branch "$BRANCH_NAME" --sha "$CI_COMMIT_SHA"
  artifacts:
    paths:
      - coverage/                     # lets you download the HTML report
    expire_in: 1 week
