services:
  frontend-dev:
    image: adalmia/sensai-frontend:dev
    ports:
      - "8502:3000"
    depends_on:
      backend-dev:
        condition: service_healthy
    # restart: unless-stopped
    networks:
      - sensai-network-dev

  backend-dev:
    image: adalmia/sensai-ai:v2-dev
    working_dir: /src
    command: bash -c "python /src/startup.py && uvicorn api.main:app --host 0.0.0.0 --port 8001"
    volumes:
      - /appdata_dev:/appdata
    ports:
      - "8002:8001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - sensai-network-dev

  public-api-dev:
    image: adalmia/sensai-ai:v2-dev
    working_dir: /src
    command: bash -c "python /src/startup.py && uvicorn api.public:app --host 0.0.0.0 --port 8001"
    volumes:
      - /appdata_dev:/appdata
    ports:
      - "8005:8001"

networks:
  sensai-network-dev:
    driver: bridge
